// Per-example RMS normalization, fixed scale, no bias; BF16 boundaries.
namespace mlp_bn16 {
__device__ float rms_reduce(float x,float*shared){for(int d=16;d;d>>=1)x+=__shfl_down_sync(0xffffffff,x,d);if((threadIdx.x&31)==0)shared[threadIdx.x>>5]=x;__syncthreads();if(threadIdx.x==0)shared[4]=shared[0]+shared[1]+shared[2]+shared[3];__syncthreads();return shared[4];}
__global__ void forward(const B*u,B*z,int rows,int m,int b,float p,unsigned seed){int r=blockIdx.x,t=threadIdx.x;__shared__ float red[5];float sq=0;for(int c=t;c<m;c+=128){float a=__bfloat162float(u[r*m+c]);sq+=a*a;}float inv=rsqrtf(rms_reduce(sq,red)/m+1e-5f);for(int c=t;c<m;c+=128){B out=__float2bfloat16_rn(fmaxf(__bfloat162float(u[r*m+c])*inv,0.f));if(p>0){float random=(pb_hash((r%b)*m+c+seed+(r/b)*101)+1.f)/4294967296.f;float v=__bfloat162float(out);out=__float2bfloat16_rn(random<p?0:(p==.1f?v*1.111111164093017578125f:v/(1-p)));}z[r*m+c]=out;}}
__global__ void backward(B*g,const B*z,const B*u,int rows,int m,float gain){int r=blockIdx.x,t=threadIdx.x;__shared__ float red[5];float sq=0;for(int c=t;c<m;c+=128){float a=__bfloat162float(u[r*m+c]);sq+=a*a;}float inv=rsqrtf(rms_reduce(sq,red)/m+1e-5f);float dot=0;for(int c=t;c<m;c+=128){int i=r*m+c;float v=__bfloat162float(z[i])>0?gain*__bfloat162float(g[i]):0;dot+=v*__bfloat162float(u[i])*inv;}float gn=rms_reduce(dot,red)/m;for(int c=t;c<m;c+=128){int i=r*m+c;float v=__bfloat162float(z[i])>0?gain*__bfloat162float(g[i]):0;g[i]=__float2bfloat16_rn(inv*(v-__bfloat162float(u[i])*inv*gn));}}
template<int M>__global__ void forward_cached(const B*u,B*z,int rows,int b,float p,unsigned seed){int r=blockIdx.x,t=threadIdx.x;__shared__ float red[5];constexpr int Count=M/128;float uv[Count],sq=0;for(int k=0;k<Count;k++){uv[k]=__bfloat162float(u[r*M+t+k*128]);sq+=uv[k]*uv[k];}float inv=rsqrtf(rms_reduce(sq,red)/M+1e-5f);for(int k=0;k<Count;k++){int c=t+k*128;B out=__float2bfloat16_rn(fmaxf(uv[k]*inv,0.f));if(p>0){float random=(pb_hash((r%b)*M+c+seed+(r/b)*101)+1.f)/4294967296.f;float v=__bfloat162float(out);out=__float2bfloat16_rn(random<p?0:(p==.1f?v*1.111111164093017578125f:v/(1-p)));}z[r*M+c]=out;}}
template<int M>__global__ void backward_cached(B*g,const B*z,const B*u,int rows,float gain){int r=blockIdx.x,t=threadIdx.x;__shared__ float red[5];constexpr int Count=M/128;float uv[Count],gv[Count],sq=0;for(int k=0;k<Count;k++){int i=r*M+t+k*128;uv[k]=__bfloat162float(u[i]);gv[k]=__bfloat162float(z[i])>0?gain*__bfloat162float(g[i]):0;sq+=uv[k]*uv[k];}float inv=rsqrtf(rms_reduce(sq,red)/M+1e-5f);float dot=0;for(int k=0;k<Count;k++)dot+=gv[k]*uv[k]*inv;float gn=rms_reduce(dot,red)/M;for(int k=0;k<Count;k++)g[r*M+t+k*128]=__float2bfloat16_rn(inv*(gv[k]-uv[k]*inv*gn));}
__device__ __forceinline__ float warp_four_reduce(float sums[4]){float x=sums[0]+sums[1]+sums[2]+sums[3];for(int d=16;d;d>>=1)x+=__shfl_down_sync(0xffffffff,x,d);return __shfl_sync(0xffffffff,x,0);}
template<int M>__global__ void forward_rowpacked(const B*u,B*z,int rows,int b,float p,unsigned seed){int lane=threadIdx.x&31,r=blockIdx.x*4+(threadIdx.x>>5);if(r>=rows)return;constexpr int Count=M/128;float uv[4][Count],sq[4]={};for(int v=0;v<4;v++)for(int k=0;k<Count;k++){int c=lane+v*32+k*128;uv[v][k]=__bfloat162float(u[r*M+c]);sq[v]+=uv[v][k]*uv[v][k];}float inv=rsqrtf(warp_four_reduce(sq)/M+1e-5f);for(int v=0;v<4;v++)for(int k=0;k<Count;k++){int c=lane+v*32+k*128;B out=__float2bfloat16_rn(fmaxf(uv[v][k]*inv,0.f));if(p>0){float random=(pb_hash((r%b)*M+c+seed+(r/b)*101)+1.f)/4294967296.f;float val=__bfloat162float(out);out=__float2bfloat16_rn(random<p?0:(p==.1f?val*1.111111164093017578125f:val/(1-p)));}z[r*M+c]=out;}}
template<int M>__global__ void backward_rowpacked(B*g,const B*z,const B*u,int rows,float gain,int b,float p,unsigned seed){int lane=threadIdx.x&31,r=blockIdx.x*4+(threadIdx.x>>5);if(r>=rows)return;constexpr int Count=M/64;float2 uv[Count],gv[Count];float sq=0;for(int k=0;k<Count;k++){int i=(r*M)/2+lane+k*32;uv[k]=__bfloat1622float2(reinterpret_cast<const __nv_bfloat162*>(u)[i]);int c=2*(lane+k*32);float rx=(pb_hash((r%b)*M+c+seed+(r/b)*101)+1.f)/4294967296.f,ry=(pb_hash((r%b)*M+c+1+seed+(r/b)*101)+1.f)/4294967296.f;float2 gg=__bfloat1622float2(reinterpret_cast<const __nv_bfloat162*>(g)[i]);gv[k]=make_float2(uv[k].x>0&&(p<=0||rx>=p)?gain*gg.x:0,uv[k].y>0&&(p<=0||ry>=p)?gain*gg.y:0);sq+=uv[k].x*uv[k].x+uv[k].y*uv[k].y;}for(int d=16;d;d>>=1)sq+=__shfl_down_sync(0xffffffff,sq,d);float inv=rsqrtf(__shfl_sync(0xffffffff,sq,0)/M+1e-5f);float dot=0;for(int k=0;k<Count;k++)dot+=gv[k].x*uv[k].x*inv+gv[k].y*uv[k].y*inv;for(int d=16;d;d>>=1)dot+=__shfl_down_sync(0xffffffff,dot,d);float gn=__shfl_sync(0xffffffff,dot,0)/M;for(int k=0;k<Count;k++){float2 v=make_float2(inv*(gv[k].x-uv[k].x*inv*gn),inv*(gv[k].y-uv[k].y*inv*gn));reinterpret_cast<__nv_bfloat162*>(g)[(r*M)/2+lane+k*32]=__float22bfloat162_rn(v);}}
inline void act(const B*u,B*z,int rows,int m,int b,float p,unsigned seed,float*stats,cudaStream_t s){switch(m){case 128:forward_rowpacked<128><<<(rows+3)/4,128,0,s>>>(u,z,rows,b,p,seed);break;case 256:forward_rowpacked<256><<<(rows+3)/4,128,0,s>>>(u,z,rows,b,p,seed);break;case 512:forward_rowpacked<512><<<(rows+3)/4,128,0,s>>>(u,z,rows,b,p,seed);break;default:forward<<<rows,128,0,s>>>(u,z,rows,m,b,p,seed);}}
inline void back(B*g,const B*z,const B*u,int rows,int m,int b,float gain,const float*stats,cudaStream_t s,float p=0,unsigned seed=0){switch(m){case 128:backward_rowpacked<128><<<(rows+3)/4,128,0,s>>>(g,z,u,rows,gain,b,p,seed);break;case 256:backward_rowpacked<256><<<(rows+3)/4,128,0,s>>>(g,z,u,rows,gain,b,p,seed);break;case 512:backward_rowpacked<512><<<(rows+3)/4,128,0,s>>>(g,z,u,rows,gain,b,p,seed);break;default:backward<<<rows,128,0,s>>>(g,z,u,rows,m,gain);}}
}
