// Chunked parallel BN statistics and row-owned apply. FP32 association differs from scalar16-group BN.
namespace bn_staged_back128 {
__device__ float2 loadpair(const B*p){return __bfloat1622float2(*reinterpret_cast<const __nv_bfloat162*>(p));}
__device__ void storepair(B*p,float x,float y){*reinterpret_cast<__nv_bfloat162*>(p)=__floats2bfloat162_rn(x,y);}
template<bool Gradient>__global__ void partial_stats(const B*u,const B*z,const B*g,float*partial,const float*stats,int b,int m,float gain,int chunks){int lane=threadIdx.x&31,group=threadIdx.x>>5,e=blockIdx.y,chunk=blockIdx.z,c=blockIdx.x*64+lane*2;__shared__ float sums[8][64],weighted[8][64];float2 a=make_float2(0,0),q=make_float2(0,0),mu,iv;if constexpr(Gradient){mu=*reinterpret_cast<const float2*>(stats+e*4*m+c);iv=*reinterpret_cast<const float2*>(stats+e*4*m+m+c);}int end=min(b,(chunk+1)*256);for(int r=chunk*256+group;r<end;r+=8){int i=(e*b+r)*m+c;float2 x=loadpair(u+i);if constexpr(Gradient){float2 mask=loadpair(z+i),v=loadpair(g+i);v.x=mask.x>0?gain*v.x:0;v.y=mask.y>0?gain*v.y:0;a.x+=v.x;a.y+=v.y;q.x+=v.x*(x.x-mu.x)*iv.x;q.y+=v.y*(x.y-mu.y)*iv.y;}else{a.x+=x.x;a.y+=x.y;q.x+=x.x*x.x;q.y+=x.y*x.y;}}sums[group][lane*2]=a.x;sums[group][lane*2+1]=a.y;weighted[group][lane*2]=q.x;weighted[group][lane*2+1]=q.y;__syncthreads();if(threadIdx.x<64){int col=threadIdx.x;float s=0,w=0;for(int row=0;row<8;row++){s+=sums[row][col];w+=weighted[row][col];}int offset=(e*chunks+chunk)*2*m+blockIdx.x*64+col;partial[offset]=s;partial[offset+m]=w;}}
template<bool Gradient>__global__ void reduce_stats(const float*partial,float*stats,int b,int m,int E,int chunks){int c=blockIdx.x*256+threadIdx.x,e=blockIdx.y;if(c>=m)return;float a=0,q=0;for(int k=0;k<chunks;k++){int i=(e*chunks+k)*2*m+c;a+=partial[i];q+=partial[i+m];}a/=b;q/=b;if constexpr(Gradient){stats[e*4*m+2*m+c]=a;stats[e*4*m+3*m+c]=q;}else{stats[e*4*m+c]=a;stats[e*4*m+m+c]=rsqrtf(fmaxf(q-a*a,0.f)+1e-5f);}}
template<bool FastGain>__global__ void apply_forward(const B*u,B*z,const float*stats,int rows,int m,int b,float p,unsigned seed){int r=blockIdx.x*4+(threadIdx.x>>5),lane=threadIdx.x&31;if(r>=rows)return;int e=r/b,local=r%b;for(int c=lane*2;c<m;c+=64){float2 v=loadpair(u+r*m+c),mu=*reinterpret_cast<const float2*>(stats+e*4*m+c),iv=*reinterpret_cast<const float2*>(stats+e*4*m+m+c);float a[2]={__bfloat162float(__float2bfloat16_rn(fmaxf((v.x-mu.x)*iv.x,0.f))),__bfloat162float(__float2bfloat16_rn(fmaxf((v.y-mu.y)*iv.y,0.f)))};for(int j=0;j<2;j++)if(p>0){float random=(pb_hash(local*m+c+j+seed+e*101)+1.f)/4294967296.f;if constexpr(FastGain)a[j]=random<p?0:a[j]*1.111111164093017578125f;else a[j]=random<p?0:a[j]/(1-p);}storepair(z+r*m+c,a[0],a[1]);}}
__device__ unsigned pack(float x,float y){union{__nv_bfloat162 bf;unsigned u;}v;v.bf=__floats2bfloat162_rn(x,y);return v.u;}
__device__ float component(float4 v,int i){return i==0?v.x:i==1?v.y:i==2?v.z:v.w;}
__global__ void apply_backward(B*g,const B*z,const B*u,const float*stats,int rows,int m,int b,float gain){int r=blockIdx.x*4+(threadIdx.x>>5),lane=threadIdx.x&31;if(r>=rows)return;int e=r/b;for(int c=lane*8;c<m;c+=256){int i=r*m+c;uint4 raw=*reinterpret_cast<const uint4*>(u+i),mask=*reinterpret_cast<const uint4*>(z+i),grad=*reinterpret_cast<const uint4*>(g+i);unsigned rawparts[4]={raw.x,raw.y,raw.z,raw.w},maskparts[4]={mask.x,mask.y,mask.z,mask.w},gradparts[4]={grad.x,grad.y,grad.z,grad.w};uint4 out;unsigned*res=&out.x;
#pragma unroll
for(int half=0;half<2;half++){int ch=c+half*4;float4 mu=*reinterpret_cast<const float4*>(stats+e*4*m+ch),iv=*reinterpret_cast<const float4*>(stats+e*4*m+m+ch),gm=*reinterpret_cast<const float4*>(stats+e*4*m+2*m+ch),gx=*reinterpret_cast<const float4*>(stats+e*4*m+3*m+ch);
#pragma unroll
for(int pair=0;pair<2;pair++){int k=half*2+pair;union{unsigned u;__nv_bfloat162 bf;}a,v,w;a.u=rawparts[k];v.u=maskparts[k];w.u=gradparts[k];float2 x=__bfloat1622float2(a.bf),zv=__bfloat1622float2(v.bf),gv=__bfloat1622float2(w.bf);int j=pair*2;float g0=zv.x>0?gain*gv.x:0,g1=zv.y>0?gain*gv.y:0;res[k]=pack(component(iv,j)*(g0-component(gm,j)-(x.x-component(mu,j))*component(iv,j)*component(gx,j)),component(iv,j+1)*(g1-component(gm,j+1)-(x.y-component(mu,j+1))*component(iv,j+1)*component(gx,j+1)));}}*reinterpret_cast<uint4*>(g+i)=out;}}
inline void act(const B*u,B*z,int rows,int m,int b,float p,unsigned seed,float*stats,float*partial,cudaStream_t s){int E=rows/b,chunks=(b+255)/256;partial_stats<false><<<dim3(m/64,E,chunks),256,0,s>>>(u,nullptr,nullptr,partial,stats,b,m,0,chunks);reduce_stats<false><<<dim3((m+255)/256,E),256,0,s>>>(partial,stats,b,m,E,chunks);if(p==.1f)apply_forward<true><<<(rows+3)/4,128,0,s>>>(u,z,stats,rows,m,b,p,seed);else apply_forward<false><<<(rows+3)/4,128,0,s>>>(u,z,stats,rows,m,b,p,seed);}
inline void back(B*g,const B*z,const B*u,int rows,int m,int b,float gain,float*stats,float*partial,cudaStream_t s){int E=rows/b,chunks=(b+255)/256;partial_stats<true><<<dim3(m/64,E,chunks),256,0,s>>>(u,z,g,partial,stats,b,m,gain,chunks);reduce_stats<true><<<dim3((m+255)/256,E),256,0,s>>>(partial,stats,b,m,E,chunks);apply_backward<<<(rows+3)/4,128,0,s>>>(g,z,u,stats,rows,m,b,gain);}
}
