#define PB_CLIP 0.03f
// Persistent BF16/cuBLAS control: every floating tensor except API input is BF16.
#include <cuda_runtime.h>
#include <cuda_bf16.h>
#include <cublas_v2.h>
#include <math.h>
#include <stdexcept>
using B=__nv_bfloat16;
__device__ unsigned pb_hash(unsigned a){a^=a>>16;a*=0x7feb352d;a^=a>>15;a*=0x846ca68b;return a^(a>>16);}
__global__ void pb_input(const float*x,B*z,int n,int d,int original,float fixed_scale){int r=blockIdx.x,t=threadIdx.x;if(fixed_scale>=0){for(int j=t;j<d;j+=256)z[r*d+j]=__float2bfloat16_rn(j<original?x[r*original+j]*fixed_scale:0);return;}__shared__ float red[256];float v=0;for(int j=t;j<original;j+=256)v+=x[r*original+j]*x[r*original+j];red[t]=v;__syncthreads();for(int s=128;s;s>>=1){if(t<s)red[t]+=red[t+s];__syncthreads();}float scale=sqrtf(float(original)/fmaxf(red[0],1e-20f));for(int j=t;j<d;j+=256)z[r*d+j]=__float2bfloat16_rn(j<original?x[r*original+j]*scale:0);}
__global__ void pb_init(B*w,B*h,int d,int m,unsigned seed){int i=blockIdx.x*256+threadIdx.x;if(i<m*d){float a=(pb_hash(i+seed)+1.f)/4294967296.f,b=(pb_hash(i+seed+123456)+1.f)/4294967296.f;w[i]=__float2bfloat16_rn(sqrtf(-2*logf(a))*cosf(6.2831853f*b)/sqrtf(float(d)));}if(i<m*10)h[i]=__float2bfloat16_rn(0);}
// Gaussian, paired, signed Hadamard, Xavier normal, Kaiming normal, Xavier with ReLU gain.
__global__ void pb_init_weights(B*w,int d,int m,unsigned seed,float gain,int kind,int original=0){int i=blockIdx.x*256+threadIdx.x;if(i>=m*d)return;int physical=i;int row=i/d,col=i%d;if(original){if(col>=original){w[i]=__float2bfloat16_rn(0);return;}i=row*original+col;d=original;}float value;
 if(kind==2){int width=1;while(width<d)width*=2;unsigned signs=__popc((row%width)&col)+(pb_hash(col+(row/width)*100003+seed+451)&1)+(pb_hash(row+seed+917)&1);value=(signs&1)?-1.f:1.f;}
 else{int index=kind==1?(row%(m/2))*d+col:i;float a=(pb_hash(index+seed)+1.f)/4294967296.f,b=(pb_hash(index+seed+123456)+1.f)/4294967296.f;value=sqrtf(-2*logf(a))*cosf(6.2831853f*b);if(kind==1&&row>=m/2)value=-value;}
 float scaled=gain*value/sqrtf(float(d));if(kind==3||kind==5)scaled*=sqrtf((kind==5?4.f:2.f)*d/(d+m));else if(kind==4)scaled*=sqrtf(2.f);w[physical]=__float2bfloat16_rn(scaled);}
__global__ void pb_init_head(B*h,int m,unsigned seed,float gain){int i=blockIdx.x*256+threadIdx.x;if(i>=m*10)return;float a=(pb_hash(i+seed)+1.f)/4294967296.f,b=(pb_hash(i+seed+123456)+1.f)/4294967296.f;h[i]=__float2bfloat16_rn(gain*sqrtf(-2*logf(a))*cosf(6.2831853f*b)/sqrtf(float(m)));}
template<int C>struct Pack;template<>struct Pack<8>{union{uint4 vec;B x[8];};};template<>struct Pack<4>{union{uint2 vec;B x[4];};};
__global__ void pb_error(B*e,const long*y,int n,int off,int total,float mix,unsigned seed,int E,int base){int r=blockIdx.x*128+threadIdx.x;if(r>=n)return;int batch=n/E,local=r%batch;seed+=(r/batch)*101;int partner=pb_hash(local+seed)%total;float a[10],mx=-INFINITY,sum=0;for(int j=0;j<10;j++){a[j]=__bfloat162float(e[r*10+j]);mx=fmaxf(mx,a[j]);}for(int j=0;j<10;j++)sum+=expf(a[j]-mx);for(int j=0;j<10;j++)e[r*10+j]=__float2bfloat16_rn(expf(a[j]-mx)/sum-((1-mix)*(y[(off+local%base)%total]==j)+mix*(y[partner]==j)));}
__global__ void pb_mix_input(const B*x,B*out,int batch,int d,int off,int total,float mix,unsigned seed){int i=blockIdx.x*256+threadIdx.x;if(i>=batch*d)return;int r=i/d,c=i%d,partner=pb_hash(r+seed)%total;out[i]=__float2bfloat16_rn((1-mix)*__bfloat162float(x[(off+r)*d+c])+mix*__bfloat162float(x[partner*d+c]));}
__global__ void pb_update(B*w,const B*g,B*v,int size,int batch,float lr,float momentum,float wd){int i=blockIdx.x*256+threadIdx.x;if(i>=size)return;float wi=__bfloat162float(w[i]),grad=fminf(PB_CLIP,fmaxf(-PB_CLIP,__bfloat162float(g[i])/batch))+wd*wi;B vel=__float2bfloat16_rn(momentum*__bfloat162float(v[i])+grad);v[i]=vel;w[i]=__float2bfloat16_rn(wi-lr*(grad+momentum*__bfloat162float(vel)));}
// One launch updates all parameter groups; each thread reads/writes two BF16 values.
__global__ void pb_update_all(B*w1,B*w2,B*h,const B*g1,const B*g2,const B*gh,B*v1,B*v2,B*vh,int d,int m,int E,int batch,float lr1,float lr2,float hlr,float momentum,float wd,bool nesterov,float*sw1,float*sw2,float*swh,bool collect){
 int pair=blockIdx.x*256+threadIdx.x,i=pair*2,total=E*(m*d+m*m+m*10);if(i>=total)return;
 B*w,*v;const B*g;float lr;float*sw;
 if(i<E*m*d){w=w1;g=g1;v=v1;lr=lr1;sw=sw1;}
 else if(i<E*(m*d+m*m)){i-=E*m*d;w=w2;g=g2;v=v2;lr=lr2;sw=sw2;}
 else{i-=E*(m*d+m*m);w=h;g=gh;v=vh;lr=hlr*256/m;sw=swh;}
 float2 weights=__bfloat1622float2(*reinterpret_cast<const __nv_bfloat162*>(w+i));
 float2 grads=__bfloat1622float2(*reinterpret_cast<const __nv_bfloat162*>(g+i));
 float2 velocities=__bfloat1622float2(*reinterpret_cast<const __nv_bfloat162*>(v+i));
 float gx=fminf(PB_CLIP,fmaxf(-PB_CLIP,grads.x/batch))+wd*weights.x,gy=fminf(PB_CLIP,fmaxf(-PB_CLIP,grads.y/batch))+wd*weights.y;
 B vx=__float2bfloat16_rn(momentum*velocities.x+gx),vy=__float2bfloat16_rn(momentum*velocities.y+gy);
 *reinterpret_cast<__nv_bfloat162*>(v+i)=__halves2bfloat162(vx,vy);
 B wx=__float2bfloat16_rn(weights.x-lr*(nesterov?gx+momentum*__bfloat162float(vx):__bfloat162float(vx)));
 B wy=__float2bfloat16_rn(weights.y-lr*(nesterov?gy+momentum*__bfloat162float(vy):__bfloat162float(vy)));
 *reinterpret_cast<__nv_bfloat162*>(w+i)=__halves2bfloat162(wx,wy);if(collect){sw[i]+=__bfloat162float(wx);sw[i+1]+=__bfloat162float(wy);}
}
__global__ void pb_dropout(B*z,int count,float p,unsigned seed){int i=blockIdx.x*256+threadIdx.x;if(i<count){float u=(pb_hash(i+seed)+1.f)/4294967296.f;z[i]=__float2bfloat16_rn(u<p?0:__bfloat162float(z[i])/(1-p));}}
__global__ void pb_noise(const B*x,B*aug,int count,float sd,unsigned seed){int i=blockIdx.x*256+threadIdx.x;if(i<count){float a=(pb_hash(i+seed)+1.f)/4294967296.f,b=(pb_hash(i+seed+123456)+1.f)/4294967296.f;float noise=sqrtf(-2*logf(a))*cosf(6.2831853f*b);aug[i]=__float2bfloat16_rn(__bfloat162float(x[i])+sd*noise);}}
// Preserve the intermediate BF16 rounding while eliminating the mix/noise buffer round trip.
__global__ void pb_mix_noise(const B*x,B*out,int batch,int d,int off,int total,float mix,float sd,unsigned mix_seed,unsigned noise_seed){int i=blockIdx.x*256+threadIdx.x;if(i>=batch*d)return;int r=i/d,c=i%d,partner=pb_hash(r+mix_seed)%total;B mixed=__float2bfloat16_rn((1-mix)*__bfloat162float(x[(off+r)*d+c])+mix*__bfloat162float(x[partner*d+c]));float a=(pb_hash(i+noise_seed)+1.f)/4294967296.f,b=(pb_hash(i+noise_seed+123456)+1.f)/4294967296.f;float noise=sqrtf(-2*logf(a))*cosf(6.2831853f*b);out[i]=__float2bfloat16_rn(__bfloat162float(mixed)+sd*noise);}
__global__ void pb_predict(const B*e,long*out,int n){int r=blockIdx.x*128+threadIdx.x;if(r>=n)return;int best=0;for(int j=1;j<10;j++)if(__bfloat162float(e[r*10+j])>__bfloat162float(e[r*10+best]))best=j;out[r]=best;}
static thread_local cublasHandle_t pb_handle=nullptr;
void prepare_pb_handle(cudaStream_t s){if(!pb_handle&&cublasCreate(&pb_handle)!=CUBLAS_STATUS_SUCCESS)throw std::runtime_error("BF16 state cublasCreate failed");if(cublasSetStream(pb_handle,s)!=CUBLAS_STATUS_SUCCESS)throw std::runtime_error("BF16 state set stream failed");}
static void mm(const B*a,const B*b,B*out,int m,int n,int k,bool at,bool bt,int E,bool shared_a=false,bool shared_b=false){float alpha=1,beta=0;auto status=cublasGemmStridedBatchedEx(pb_handle,bt?CUBLAS_OP_N:CUBLAS_OP_T,at?CUBLAS_OP_T:CUBLAS_OP_N,n,m,k,&alpha,b,CUDA_R_16BF,bt?n:k,shared_b?0:((long long)n*k),a,CUDA_R_16BF,at?m:k,shared_a?0:((long long)m*k),&beta,out,CUDA_R_16BF,n,(long long)m*n,E,CUBLAS_COMPUTE_32F,CUBLAS_GEMM_DEFAULT_TENSOR_OP);if(status!=CUBLAS_STATUS_SUCCESS)throw std::runtime_error("ensemble BF16 GEMM failed");}
__global__ void ensemble_input(const B*x,B*out,int batch,int d,int off,int total,float mix,float sd,unsigned seed,int E,int base,int original){int i=blockIdx.x*256+threadIdx.x;if(i>=E*batch*d)return;int member=i/(batch*d),local=i%(batch*d),r=local/d,c=local%d;if(c>=original+10){out[i]=__float2bfloat16_rn(0);return;}int noise_index=r*original+c;unsigned ms=seed+member*101+999,ns=seed+member*101+777;int partner=pb_hash(r+ms)%total;B v=x[((off+r%base)%total)*d+c];if(mix>0)v=__float2bfloat16_rn((1-mix)*__bfloat162float(v)+mix*__bfloat162float(x[partner*d+c]));if(sd>0&&c<original){float a=(pb_hash(noise_index+ns)+1.f)/4294967296.f,b=(pb_hash(noise_index+ns+123456)+1.f)/4294967296.f;v=__float2bfloat16_rn(__bfloat162float(v)+sd*sqrtf(-2*logf(a))*cosf(6.2831853f*b));}out[i]=v;}
__global__ void ensemble_predict(const B*logits,long*out,int n,int E){int r=blockIdx.x*128+threadIdx.x;if(r>=n)return;int best=0;float bestv=-INFINITY;for(int c=0;c<10;c++){float sum=0;for(int member=0;member<E;member++)sum+=__bfloat162float(logits[(member*n+r)*10+c]);if(sum>bestv){bestv=sum;best=c;}}out[r]=best;}
__global__ void swa_finalize(B*w1,B*w2,B*h,const float*s1,const float*s2,const float*sh,int d,int m,int E,int count){int i=blockIdx.x*256+threadIdx.x;if(i>=E*(m*d+m*m+m*10))return;B*w;const float*s;if(i<E*m*d){w=w1;s=s1;}else if(i<E*(m*d+m*m)){i-=E*m*d;w=w2;s=s2;}else{i-=E*(m*d+m*m);w=h;s=sh;}w[i]=__float2bfloat16_rn(s[i]/count);}
__global__ void dictionary_targets(const long*y,B*targets,int n){int i=blockIdx.x*256+threadIdx.x;if(i<n*10)targets[i]=__float2bfloat16_rn(y[i/10]==i%10?1.f:0.f);}
__global__ void dictionary_normalize(B*cent,int d,int original){int label=blockIdx.x,lane=threadIdx.x;float sum=0;for(int j=lane;j<original;j+=32){float v=__bfloat162float(cent[label*d+j]);sum+=v*v;}for(int shift=16;shift;shift>>=1)sum+=__shfl_down_sync(0xffffffff,sum,shift);float norm=sqrtf(__shfl_sync(0xffffffff,sum,0)+1e-20f);for(int j=lane;j<d;j+=32)cent[label*d+j]=__float2bfloat16_rn(j<original?__bfloat162float(cent[label*d+j])/norm:0);}
__global__ void dictionary_append(B*x,const B*cent,int rows,int d,int original,float scale){int r=blockIdx.x*4+(threadIdx.x>>5),lane=threadIdx.x&31;if(r>=rows)return;for(int label=0;label<10;label++){float sum=0;for(int j=lane;j<original;j+=32)sum+=__bfloat162float(x[r*d+j])*__bfloat162float(cent[label*d+j]);for(int shift=16;shift;shift>>=1)sum+=__shfl_down_sync(0xffffffff,sum,shift);if(lane==0)x[r*d+original+label]=__float2bfloat16_rn(scale*sum);}}
__global__ void dictionary_init(B*w,const B*cent,const B*x,int original,int d,int m,int n,unsigned seed,int kind,float jitter,float gain){int i=blockIdx.x*256+threadIdx.x;if(i>=m*d)return;int row=i/d,col=i%d;if(col>=original){w[i]=__float2bfloat16_rn(0);return;}float a=(pb_hash(row*original+col+seed)+1.f)/4294967296.f,b=(pb_hash(row*original+col+seed+123456)+1.f)/4294967296.f;float random=sqrtf(-2*logf(a))*cosf(6.2831853f*b)/sqrtf(float(original));float data=kind==6?__bfloat162float(cent[(row%10)*d+col]):__bfloat162float(x[(pb_hash(row+seed)%n)*d+col])/sqrtf(float(original));w[i]=__float2bfloat16_rn(gain*(sqrtf(fmaxf(0,1-jitter*jitter))*data+jitter*random));}
__global__ void update_extra(B*w,const B*g,B*v,float*sw,int count,int batch,float lr,float momentum,float wd,bool nesterov,bool collect){int i=blockIdx.x*256+threadIdx.x;if(i>=count)return;float wi=__bfloat162float(w[i]),grad=fminf(PB_CLIP,fmaxf(-PB_CLIP,__bfloat162float(g[i])/batch))+wd*wi;B vel=__float2bfloat16_rn(momentum*__bfloat162float(v[i])+grad);v[i]=vel;B value=__float2bfloat16_rn(wi-lr*(nesterov?grad+momentum*__bfloat162float(vel):__bfloat162float(vel)));w[i]=value;if(collect)sw[i]+=__bfloat162float(value);}
__global__ void finalize_extra(B*w,const float*sw,int count,int num){int i=blockIdx.x*256+threadIdx.x;if(i<count)w[i]=__float2bfloat16_rn(sw[i]/num);}
#include "mlp_batchnorm16.cuh"
#include "mlp_batchnorm16_staged.cuh"
#include "mlp_batchnorm16_staged_fastgain.cuh"
#include "mlp_batchnorm16_staged_back128.cuh"
void launch_pb(const float*x,const long*y,const float*q,long*out,B*tx,B*tq,B*w1,B*w2,B*h,B*u1,B*u2,B*z1,B*z2,B*du1,B*du2,B*dw1,B*dw2,B*dh,B*err,B*logits,B*v1,B*v2,B*vh,B*aug,B*targets,B*centroids,float*sw1,float*sw2,float*swh,B*w3,B*u3,B*z3,B*du3,B*dw3,B*v3,float*sw3,float*stats1,float*stats2,float*stats3,float*partial,int n,int nq,int d,int original,int m,int E,int batch,int views,int steps,int schedule,float lr1,float lr2,float hlr,float momentum,float wd,float dropout,float noise,float input_scale,float mix,float init_gain,float head_gain,int init_kind,float swa_fraction,float dictionary_scale,float data_noise,unsigned seed,cudaStream_t s){
 int swa_count=swa_fraction>0?max(1,int(steps*swa_fraction)):0;bool nesterov=schedule<3;schedule%=3;prepare_pb_handle(s);pb_input<<<n,256,0,s>>>(x,tx,n,d,original,input_scale);pb_input<<<nq,256,0,s>>>(q,tq,nq,d,original,input_scale);dictionary_targets<<<(n*10+255)/256,256,0,s>>>(y,targets,n);mm(targets,tx,centroids,10,d,n,true,true,1);dictionary_normalize<<<10,32,0,s>>>(centroids,d,original);dictionary_append<<<(n+3)/4,128,0,s>>>(tx,centroids,n,d,original,dictionary_scale);dictionary_append<<<(nq+3)/4,128,0,s>>>(tq,centroids,nq,d,original,dictionary_scale);for(int member=0;member<E;member++){unsigned es=seed+member*101;if(init_kind>=6)dictionary_init<<<(m*d+255)/256,256,0,s>>>(w1+member*m*d,centroids,tx,original,d,m,n,es,init_kind,data_noise,init_gain);else pb_init_weights<<<(m*d+255)/256,256,0,s>>>(w1+member*m*d,d,m,es,init_gain,init_kind,original+10);pb_init_weights<<<(m*m+255)/256,256,0,s>>>(w2+member*m*m,m,m,es+123123,init_gain,init_kind);pb_init_weights<<<(m*m+255)/256,256,0,s>>>(w3+member*m*m,m,m,es+789789,init_gain,init_kind);pb_init_head<<<(m*10+255)/256,256,0,s>>>(h+member*m*10,m,es+456456,head_gain);}cudaMemsetAsync(v1,0,E*m*d*2,s);cudaMemsetAsync(v2,0,E*m*m*2,s);cudaMemsetAsync(vh,0,E*m*10*2,s);cudaMemsetAsync(v3,0,E*m*m*2,s);if(swa_count){cudaMemsetAsync(sw1,0,E*m*d*4,s);cudaMemsetAsync(sw2,0,E*m*m*4,s);cudaMemsetAsync(swh,0,E*m*10*4,s);cudaMemsetAsync(sw3,0,E*m*m*4,s);}
 for(int t=0;t<steps;t++){float decay=schedule==1?(.05f+.95f*.5f*(1+cosf(3.141592653589793f*t/fmaxf(steps-1,1)))):(schedule==2?(t*100>=steps*85?.01f:(t*100>=steps*60?.1f:1.f)):1.f);int off=(t*batch)%n,base=min(batch,n),b=base*views;const B*xb=aug;ensemble_input<<<(E*b*d+255)/256,256,0,s>>>(tx,aug,b,d,off,n,mix,noise,seed+t*100003,E,base,original);
 mm(xb,w1,u1,b,m,d,false,false,E);bn_staged_back128::act(u1,z1,E*b,m,b,dropout,seed+t*100003+111,stats1,partial,s);mm(z1,w2,u2,b,m,m,false,false,E);bn_staged_back128::act(u2,z2,E*b,m,b,dropout,seed+t*100003+333,stats2,partial,s);mm(z2,w3,u3,b,m,m,false,false,E);bn_staged_back128::act(u3,z3,E*b,m,b,dropout,seed+t*100003+555,stats3,partial,s);mm(z3,h,err,b,10,m,false,true,E);pb_error<<<(E*b+127)/128,128,0,s>>>(err,y,E*b,off,n,mix,seed+t*100003+999,E,base);
 mm(z3,err,dh,m,10,b,true,true,E);mm(err,h,du3,b,m,10,false,false,E);bn_staged_back128::back(du3,z3,u3,E*b,m,b,1/(1-dropout),stats3,partial,s);mm(du3,z2,dw3,m,m,b,true,true,E);mm(du3,w3,du2,b,m,m,false,true,E);bn_staged_back128::back(du2,z2,u2,E*b,m,b,1/(1-dropout),stats2,partial,s);mm(du2,z1,dw2,m,m,b,true,true,E);mm(du2,w2,du1,b,m,m,false,true,E);bn_staged_back128::back(du1,z1,u1,E*b,m,b,1/(1-dropout),stats1,partial,s);mm(du1,xb,dw1,m,d,b,true,true,E);
 pb_update_all<<<(E*(m*d+m*m+m*10)/2+255)/256,256,0,s>>>(w1,w2,h,dw1,dw2,dh,v1,v2,vh,d,m,E,b,decay*lr1,decay*lr2,decay*hlr,momentum,wd,nesterov,sw1,sw2,swh,swa_count&&t>=steps-swa_count);update_extra<<<(E*m*m+255)/256,256,0,s>>>(w3,dw3,v3,sw3,E*m*m,b,decay*lr2,momentum,wd,nesterov,swa_count&&t>=steps-swa_count);
 }
 if(swa_count&&steps>0)swa_finalize<<<(E*(m*d+m*m+m*10)+255)/256,256,0,s>>>(w1,w2,h,sw1,sw2,swh,d,m,E,swa_count);
 if(swa_count&&steps>0)finalize_extra<<<(E*m*m+255)/256,256,0,s>>>(w3,sw3,E*m*m,swa_count);
 mm(tq,w1,u1,nq,m,d,false,false,E,true);bn_staged_back128::act(u1,z1,E*nq,m,nq,0,0,stats1,partial,s);mm(z1,w2,u2,nq,m,m,false,false,E);bn_staged_back128::act(u2,z2,E*nq,m,nq,0,0,stats2,partial,s);mm(z2,w3,u3,nq,m,m,false,false,E);bn_staged_back128::act(u3,z3,E*nq,m,nq,0,0,stats3,partial,s);mm(z3,h,logits,nq,10,m,false,true,E);ensemble_predict<<<(nq+127)/128,128,0,s>>>(logits,out,nq,E);
}

