#!/usr/bin/env python3
"""Execute validated affine v4 IL as ordered, scalar FP32 C++ instructions.

The generated code implements the input document, not a model-specific algebraic
rewrite. Every leaf reads its operands before its destination write. ``eq``
compares raw words, ``lt`` compares FP32 values, and select copies raw words.
No reduction reordering, fused multiply-add, or approximate arithmetic is used.
The caller supplies ``affine.py`` from the submission scorer on its import path.
"""
from __future__ import annotations

import argparse
import ctypes
import hashlib
import json
from pathlib import Path
import subprocess
import sys
import time

import numpy as np

FLAGS = ["-std=c++17", "-O3", "-ffp-contract=off", "-fno-fast-math",
         "-frounding-math", "-fno-associative-math", "-fPIC", "-shared"]


def document_digest(document):
    return hashlib.sha256(json.dumps(document, sort_keys=True, separators=(",", ":")).encode()).hexdigest()


def emit_cpp(document):
    """Validate the document with the scorer, then emit one C++ loop per IL loop."""
    from affine import Program
    program = Program(document)
    recv_count = int(program.instructions.get("recv", 0))
    send_count = int(program.instructions.get("send", 0))
    lines = [
        "// Generated by compiler.py; primitive order follows the affine IL.",
        "#include <cstdint>", "#include <cstring>", "#include <cfenv>",
        "#if defined(__SSE__)", "#include <xmmintrin.h>", "#endif",
        "#pragma STDC FENV_ACCESS ON",
        "static_assert(sizeof(float) == sizeof(uint32_t), \"requires FP32\");",
        "static inline float f(uint32_t word) { float v; std::memcpy(&v, &word, 4); return v; }",
        "static inline uint32_t u(float v) { uint32_t word; std::memcpy(&word, &v, 4); return word; }",
        f'extern "C" const char* cg_il_program_sha256() {{ return "{document_digest(document)}"; }}',
        f'extern "C" uint64_t cg_il_words() {{ return {program.words + 1}ULL; }}',
        f'extern "C" uint64_t cg_il_input_words() {{ return {recv_count}ULL; }}',
        f'extern "C" uint64_t cg_il_output_words() {{ return {send_count}ULL; }}',
        'extern "C" int cg_il_run(uint32_t* m, uint64_t nm, const uint32_t* in, uint64_t ni, uint32_t* out, uint64_t no) {',
        f"  if (nm != {program.words + 1}ULL || ni != {recv_count}ULL || no != {send_count}ULL) return 1;",
        "  fenv_t old_env; if (std::fegetenv(&old_env) != 0) return 2;",
        "  if (std::fesetround(FE_TONEAREST) != 0) return 3;",
        "#if defined(__SSE__)",
        "  const unsigned old_mxcsr = _mm_getcsr();",
        "  _mm_setcsr(old_mxcsr & ~(unsigned(1 << 15) | unsigned(1 << 6))); // no FTZ or DAZ",
        "#endif",
        f"  std::memset(m, 0, {program.words + 1}ULL * sizeof(uint32_t));",
        "  uint64_t ip = 0, op = 0;",
    ]
    loop_counter = 0

    def address(operand, scope):
        base, _ = program.regions[operand["region"]]
        pieces = [str(base + operand["offset"])]
        for var, coeff in operand["coefficients"].items():
            if coeff:
                pieces.append(f"({coeff}LL * {scope[var]})")
        return "m[" + " + ".join(pieces) + "]"

    def visit(body, scope, indent):
        nonlocal loop_counter
        pad = "  " * indent
        for node in body:
            if "loop" in node:
                ident = f"v{loop_counter}"
                loop_counter += 1
                start, stop = node["start"], node["start"] + node["count"]
                if not -(1 << 63) <= start <= stop < (1 << 63):
                    raise ValueError("C++ executor requires loop bounds representable as int64")
                lines.append(f"{pad}for (int64_t {ident} = {start}LL; {ident} < {stop}LL; ++{ident}) {{")
                visit(node["body"], {**scope, node["loop"]: ident}, indent + 1)
                lines.append(pad + "}")
                continue
            op = node["op"]
            src = [address(operand, scope) for operand in node.get("src", [])]
            dst = address(node["dst"], scope) if "dst" in node else None
            if op == "set":
                statement = f"{dst} = {node['imm']}U;"
            elif op == "recv":
                statement = f"{dst} = in[ip++];"
            elif op == "send":
                statement = f"out[op++] = {src[0]};"
            elif op == "copy":
                statement = f"{dst} = {src[0]};"
            elif op in ("add", "sub", "mul", "div"):
                symbol = {"add": "+", "sub": "-", "mul": "*", "div": "/"}[op]
                statement = f"{dst} = u(f({src[0]}) {symbol} f({src[1]}));"
            elif op == "cmp":
                predicate = node.get("predicate", "lt")
                if predicate == "eq":
                    statement = f"{dst} = uint32_t({src[0]} == {src[1]});"
                elif predicate == "lt":
                    statement = f"{dst} = uint32_t(f({src[0]}) < f({src[1]}));"
                else:
                    raise ValueError(f"Reference execute does not support cmp predicate {predicate!r}")
            elif op == "select":
                statement = f"{dst} = ({src[0]} != 0U) ? {src[1]} : {src[2]};"
            else:
                raise ValueError(f"Unsupported opcode {op}")
            lines.append(pad + statement)

    visit(document["body"], {}, 1)
    lines.extend([
        "#if defined(__SSE__)", "  _mm_setcsr(old_mxcsr);", "#endif",
        "  if (std::fesetenv(&old_env) != 0) return 4;",
        f"  return (ip == {recv_count}ULL && op == {send_count}ULL) ? 0 : 5;",
        "}", "",
    ])
    return "\n".join(lines)


def compile_shared(document, output_dir, compiler="g++"):
    """Write source, shared library and compiler provenance under output_dir."""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    source = output_dir / "program.cpp"
    library = output_dir / "program.so"
    source.write_text(emit_cpp(document))
    command = [compiler, *FLAGS, str(source), "-o", str(library)]
    subprocess.run(command, check=True)
    version = subprocess.run([compiler, "--version"], check=True, capture_output=True, text=True).stdout.splitlines()[0]
    provenance = {"program_sha256": document_digest(document), "compiler": version,
                  "command": command, "source_sha256": hashlib.sha256(source.read_bytes()).hexdigest(),
                  "library_sha256": hashlib.sha256(library.read_bytes()).hexdigest()}
    (output_dir / "build.json").write_text(json.dumps(provenance, indent=2) + "\n")
    return library


def run_shared(library, tape_uint32, expected_digest=None):
    """Return all scratch words and all sends; address zero is unused and zero."""
    dll = ctypes.CDLL(str(Path(library).resolve()))
    for name in ("cg_il_words", "cg_il_input_words", "cg_il_output_words"):
        fn = getattr(dll, name)
        fn.argtypes, fn.restype = [], ctypes.c_uint64
    dll.cg_il_program_sha256.argtypes, dll.cg_il_program_sha256.restype = [], ctypes.c_char_p
    digest = dll.cg_il_program_sha256().decode()
    if expected_digest is not None and digest != expected_digest:
        raise ValueError("Shared library belongs to a different IL document")
    tape = np.asarray(tape_uint32)
    if tape.dtype != np.uint32:
        raise TypeError("Tape must contain raw uint32 words; convert float inputs with .view(np.uint32)")
    tape = np.ascontiguousarray(tape.reshape(-1))
    if len(tape) != dll.cg_il_input_words():
        raise ValueError(f"Tape has {len(tape)} words; program requires {dll.cg_il_input_words()}")
    memory = np.empty(dll.cg_il_words(), dtype=np.uint32)
    output = np.empty(dll.cg_il_output_words(), dtype=np.uint32)
    pointer = np.ctypeslib.ndpointer(dtype=np.uint32, ndim=1, flags="C_CONTIGUOUS")
    dll.cg_il_run.argtypes = [pointer, ctypes.c_uint64, pointer, ctypes.c_uint64, pointer, ctypes.c_uint64]
    dll.cg_il_run.restype = ctypes.c_int
    start = time.perf_counter()
    status = dll.cg_il_run(memory, len(memory), tape, len(tape), output, len(output))
    elapsed = time.perf_counter() - start
    if status:
        raise RuntimeError(f"IL executor returned error {status}")
    return {"memory": memory, "output": output, "elapsed_seconds": elapsed, "program_sha256": digest}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("program", type=Path)
    parser.add_argument("tape", nargs="?", type=Path, help="Raw uint32 .npy input tape")
    parser.add_argument("--affine-dir", type=Path)
    parser.add_argument("--emit-cpp", type=Path)
    parser.add_argument("--compile", type=Path, metavar="DIRECTORY")
    parser.add_argument("--compiler", default="g++")
    parser.add_argument("--library", type=Path)
    parser.add_argument("--output-dir", type=Path)
    args = parser.parse_args()
    if args.affine_dir:
        sys.path.insert(0, str(args.affine_dir.resolve()))
    document = json.loads(args.program.read_text())
    if args.emit_cpp:
        args.emit_cpp.parent.mkdir(parents=True, exist_ok=True)
        args.emit_cpp.write_text(emit_cpp(document))
    library = compile_shared(document, args.compile, args.compiler) if args.compile else args.library
    if args.tape:
        if not library or not args.output_dir:
            parser.error("Execution requires --library or --compile and --output-dir")
        result = run_shared(library, np.load(args.tape, allow_pickle=False), document_digest(document))
        args.output_dir.mkdir(parents=True, exist_ok=True)
        np.save(args.output_dir / "memory.npy", result.pop("memory"), allow_pickle=False)
        np.save(args.output_dir / "output.npy", result.pop("output"), allow_pickle=False)
        (args.output_dir / "execution.json").write_text(json.dumps(result, indent=2) + "\n")
        print(json.dumps(result))


if __name__ == "__main__":
    main()
