"""Dally straight-line IR -> CUDA C++ transpiler (v0, functional emulation).

Grid cells become an int8 array indexed by cell id; each IR op becomes one
load/compute/store. v0 is a correctness + timing baseline: the distance
metadata (cell idx sits at charged distance isqrt(idx-1)+1) is carried as
generated comments per op but not exploited for placement.

Supported ops (the set this demo's IR uses; parser rejects the rest):
  set N,V / copy d,a / mul d,a,b / add d,a,b / add d,a (accumulator form)
Arithmetic wraps mod 256, matching dally-eval 8-bit cell semantics; add/mul
compute in wider ints then truncate on store.

Usage:
  python dally_ir_to_cuda.py mnist3_1k_ir.txt --out mnist3_1k_kernel.cu

The emitted program is a self-contained harness:
  ./a.out inputs.bin expected.bin n_instances      bit-exactness check
  ./a.out inputs.bin expected.bin n_instances --energy reps trials
                                                   NVML energy measurement
      (idle-adjusted, 5-trial protocol from a100-grid-energy-report:
       nvmlDeviceGetTotalEnergyConsumption counter, paired loaded-idle
       baseline, per-trial aggregate reps sized to ~5 s, audit JSON)

Verification chain: expected.bin comes from mnist3_1k_demo.py's Python
reference, which dally-eval `run` already validated bit-exact (1000/1000).
The kernel check then closes the loop CUDA == Python == Rust.
"""
from __future__ import annotations

import argparse
import math
import os

HEADER = r"""// AUTO-GENERATED by dally_ir_to_cuda.py -- do not edit.
// Source IR: {ir_name}
// Grid model: cell idx sits at charged distance isqrt(idx-1)+1 from the
// processor at the origin (dally-eval cost model). v0 emulation places all
// cells in one flat array; distances are noted per op, not exploited.
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cstdint>
#include <chrono>
#ifdef WITH_NVML
#include <dlfcn.h>
typedef struct nvmlDevice_st* nvmlDevice_t;
static void* (*p_nvmlInit_v2)(void);
static void* (*p_nvmlDeviceGetHandleByIndex_v2)(unsigned, nvmlDevice_t*);
static void* (*p_nvmlDeviceGetName)(nvmlDevice_t, char*, unsigned);
static void* (*p_nvmlDeviceGetTotalEnergyConsumption)(nvmlDevice_t, unsigned long long*);
static int run_energy_protocol_impl(nvmlDevice_t h, char* name, int reps, int trials);
// resolved via dlopen so the binary needs no link-time NVML: the host
// driver's libnvidia-ml.so.1 is mounted into the container by Modal.

static uint64_t energy_mJ(nvmlDevice_t h) {{
  unsigned long long e; p_nvmlDeviceGetTotalEnergyConsumption(h, &e); return e; }}

static int run_energy_protocol(int reps, int trials) {{
  void* so = dlopen("libnvidia-ml.so.1", RTLD_NOW);
  if (!so) {{ fprintf(stderr, "NVML dlopen failed: %s\n", dlerror()); return 1; }}
  p_nvmlInit_v2 = (void* (*)(void))dlsym(so, "nvmlInit_v2");
  p_nvmlDeviceGetHandleByIndex_v2 = (void* (*)(unsigned, nvmlDevice_t*))dlsym(so, "nvmlDeviceGetHandleByIndex_v2");
  p_nvmlDeviceGetName = (void* (*)(nvmlDevice_t, char*, unsigned))dlsym(so, "nvmlDeviceGetName");
  p_nvmlDeviceGetTotalEnergyConsumption = (void* (*)(nvmlDevice_t, unsigned long long*))dlsym(so, "nvmlDeviceGetTotalEnergyConsumption");
  if (!p_nvmlInit_v2 || !p_nvmlDeviceGetTotalEnergyConsumption) {{ fprintf(stderr, "NVML symbols missing\n"); return 1; }}
  p_nvmlInit_v2();
  nvmlDevice_t h; p_nvmlDeviceGetHandleByIndex_v2(0, &h);
  char name[96] = "unknown";
  if (p_nvmlDeviceGetName) p_nvmlDeviceGetName(h, name, sizeof name);
  return run_energy_protocol_impl(h, name, reps, trials);
}}
#endif

#define N_INSTANCES {n_default}
#define N_INPUTS {n_inputs}
#define N_OUTPUTS {n_outputs}
#define N_CELLS ({max_cell} + 1)
#define N_OPS {n_ops}

static __device__ __constant__ uint16_t IN_CELLS[N_INPUTS] = {{ {in_cells} }};
static __device__ __constant__ uint16_t OUT_CELLS[N_OUTPUTS] = {{ {out_cells} }};

struct Op {{ uint8_t kind; uint16_t dst, a, b; }};

// op kinds
enum {{ OP_SET=0, OP_COPY=1, OP_ADD=2, OP_MUL=3 }};

__global__ void dally_kernel(const uint8_t* __restrict__ inputs,
                             uint8_t* __restrict__ outputs, int n) {{
  int inst = blockIdx.x * blockDim.x + threadIdx.x;
  if (inst >= n) return;
  uint8_t cells[N_CELLS];
  const uint8_t* in = inputs + (size_t)inst * N_INPUTS;
{prologue}
{op_code}
  uint8_t* out = outputs + (size_t)inst * N_OUTPUTS;
  #pragma unroll
  for (int i = 0; i < N_OUTPUTS; i++) out[i] = cells[OUT_CELLS[i]];
}}

static void load_program() {{ /* straight-line code: nothing to load */ }}

static uint8_t* d_in, * d_out;
static uint8_t* h_in, * h_exp;
static int g_n;

static void gpu_setup(const char* in_path, const char* exp_path, int n) {{
  g_n = n;
  size_t in_bytes = (size_t)n * N_INPUTS, out_bytes = (size_t)n * N_OUTPUTS;
  h_in = (uint8_t*)malloc(in_bytes);
  h_exp = (uint8_t*)malloc(out_bytes);
  FILE* f = fopen(in_path, "rb");
  if (!f || fread(h_in, 1, in_bytes, f) != in_bytes) {{ fprintf(stderr, "bad inputs file\n"); exit(1); }}
  fclose(f);
  f = fopen(exp_path, "rb");
  if (!f || fread(h_exp, 1, out_bytes, f) != out_bytes) {{ fprintf(stderr, "bad expected file\n"); exit(1); }}
  fclose(f);
  cudaMalloc(&d_in, in_bytes); cudaMalloc(&d_out, out_bytes);
  cudaMemcpy(d_in, h_in, in_bytes, cudaMemcpyHostToDevice);
  load_program();
}}

static void launch_once() {{
  int blocks = (g_n + 255) / 256;
  dally_kernel<<<blocks, 256>>>(d_in, d_out, g_n);
}}

static int check_outputs() {{
  size_t out_bytes = (size_t)g_n * N_OUTPUTS;
  uint8_t* got = (uint8_t*)malloc(out_bytes);
  cudaMemcpy(got, d_out, out_bytes, cudaMemcpyDeviceToHost);
  size_t bad = 0, first = SIZE_MAX;
  for (size_t i = 0; i < out_bytes; i++)
    if (got[i] != h_exp[i]) {{ bad++; if (first == SIZE_MAX) first = i; }}
  if (bad == 0) printf("BIT-EXACT: all %d instances x %d outputs match expected\n", g_n, N_OUTPUTS);
  else printf("MISMATCH: %zu bad bytes (first at instance %zu output %zu: got %u want %u)\n",
              bad, first / N_OUTPUTS, first % N_OUTPUTS, got[first], h_exp[first]);
  free(got);
  return bad == 0 ? 0 : 1;
}}

static double now_s() {{
  return std::chrono::duration<double>(std::chrono::steady_clock::now().time_since_epoch()).count();
}}

#ifdef WITH_NVML
static int run_energy_protocol_impl(nvmlDevice_t h, char* name, int reps, int trials) {{
  // warmup + calibration: reps<=0 means auto-size to ~5 s per trial
  launch_once(); cudaDeviceSynchronize();
  double t0 = now_s(); int cal = 2000;
  for (int i = 0; i < cal; i++) launch_once();
  cudaDeviceSynchronize();
  double per_launch = (now_s() - t0) / cal;
  if (reps <= 0) reps = (int)(5.0 / per_launch);
  printf("gpu=%s per_launch_us=%.3f reps_per_trial=%d trials=%d\n",
         name, per_launch * 1e6, reps, trials);
  double idle_W_sum = 0, raw_J_per_call_sum = 0, adj_J_per_call_sum = 0;
  double adj_vals[32], raw_vals[32], idle_vals[32], sec_vals[32];
  for (int t = 0; t < trials; t++) {{
    // loaded-idle baseline window (device initialized, kernels idle)
    uint64_t e0 = energy_mJ(h); double s0 = now_s();
    struct timespec ts{{5, 0}}; nanosleep(&ts, NULL);
    uint64_t e1 = energy_mJ(h); double s1 = now_s();
    double idle_W = (e1 - e0) / 1000.0 / (s1 - s0);
    // measurement phase: aggregate reps, sync only at boundaries
    e0 = energy_mJ(h); s0 = now_s();
    for (int i = 0; i < reps; i++) launch_once();
    cudaDeviceSynchronize();
    e1 = energy_mJ(h); s1 = now_s();
    double raw_J = (e1 - e0) / 1000.0, secs = s1 - s0;
    double adj_J = raw_J - idle_W * secs;
    idle_vals[t] = idle_W; raw_vals[t] = raw_J / reps;
    adj_vals[t] = adj_J / reps; sec_vals[t] = secs;
    idle_W_sum += idle_W; raw_J_per_call_sum += raw_J / reps; adj_J_per_call_sum += adj_J / reps;
    printf("trial %d: secs=%.3f raw_J_per_call=%.6f idle_W=%.3f adj_J_per_call=%.6f\n",
           t, secs, raw_J / reps, idle_W, adj_J / reps);
  }}
  double m_adj = adj_J_per_call_sum / trials, m_raw = raw_J_per_call_sum / trials, m_idle = idle_W_sum / trials;
  double sd = 0; for (int t = 0; t < trials; t++) sd += (adj_vals[t] - m_adj) * (adj_vals[t] - m_adj);
  sd = sqrt(sd / trials);
  printf("AUDIT_JSON:");
  printf("{{\"gpu\":\"%s\",\"n_instances\":%d,\"reps_per_trial\":%d,\"trials\":%d,",
         name, g_n, reps, trials);
  printf("\"raw_board_J_per_batch_call\":%.9f,\"idle_baseline_W\":%.6f,",
         m_raw, m_idle);
  printf("\"idle_adjusted_J_per_batch_call\":%.9f,\"trial_adj_J_stdev\":%.9f,",
         m_adj, sd);
  printf("\"idle_adjusted_J_per_inference\":%.12f,",
         m_adj / g_n);
  printf("\"trial_raw\":[");
  for (int t = 0; t < trials; t++) printf("%s%.9f", t ? "," : "", raw_vals[t]);
  printf("],\"trial_adj\":[");
  for (int t = 0; t < trials; t++) printf("%s%.9f", t ? "," : "", adj_vals[t]);
  printf("],\"trial_idle_W\":[");
  for (int t = 0; t < trials; t++) printf("%s%.6f", t ? "," : "", idle_vals[t]);
  printf("],\"trial_secs\":[");
  for (int t = 0; t < trials; t++) printf("%s%.6f", t ? "," : "", sec_vals[t]);
  printf("]}}\n");
  return 0;
}}
#endif

int main(int argc, char** argv) {{
  if (argc < 4) {{
    fprintf(stderr, "usage: %s inputs.bin expected.bin n_instances [--energy reps trials]\n", argv[0]);
    return 2;
  }}
  gpu_setup(argv[1], argv[2], atoi(argv[3]));
  launch_once(); cudaDeviceSynchronize();
  int ok = check_outputs();
#ifdef WITH_NVML
  if (argc >= 5 && !strcmp(argv[4], "--energy"))
    run_energy_protocol(argc > 5 ? atoi(argv[5]) : 0, argc > 6 ? atoi(argv[6]) : 5);
#endif
  return ok;
}}
"""


def rc(a: int) -> int:
    return math.isqrt(a - 1) + 1


def parse_ir(text: str):
    lines = [l for l in text.splitlines() if l.strip()]
    in_cells = [int(x) for x in lines[0].split(",")]
    out_cells = [int(x) for x in lines[-1].split(",")]
    ops = []
    for l in lines[1:-1]:
        parts = l.split(None, 1)
        op = parts[0]
        args = [int(x) for x in parts[1].split(",")]
        if op == "set":
            ops.append(("set", args[0], args[0], args[0], args[1]))
        elif op == "copy":
            ops.append(("copy", args[0], args[1], args[1], None))
        elif op in ("add", "mul"):
            if len(args) == 3:
                ops.append((op, args[0], args[1], args[2], None))
            else:  # accumulator form: first source is dst
                ops.append((op, args[0], args[0], args[1], None))
        else:
            raise ValueError(f"unsupported op for v0 transpiler: {op!r} (line: {l!r})")
    return in_cells, out_cells, ops


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("ir_file")
    ap.add_argument("--out", required=True)
    ap.add_argument("--n-instances", type=int, default=1000)
    args = ap.parse_args()

    with open(args.ir_file) as f:
        text = f.read()
    in_cells, out_cells, ops = parse_ir(text)
    max_cell = max(max(in_cells), max(out_cells), max(o[1] for o in ops),
                   max(max(o[2], o[3]) for o in ops))

    set_imm = ", ".join(str(o[4] & 0xFF if o[4] is not None else 0) for o in ops)
    prologue = []
    for i, c in enumerate(in_cells):
        prologue.append(f"  cells[{c}] = in[{i}];  // input read dist {rc(c)}")
    body = []
    for kind, dst, a, b, imm in ops:
        dist = f"charged read dist {rc(a)}" + (f"+{rc(b)}" if b != a else "")
        if kind == "set":
            body.append(f"  cells[{dst}] = {imm & 0xFF}u;  // set (write free)")
        elif kind == "copy":
            body.append(f"  cells[{dst}] = cells[{a}];  // copy, {dist}")
        elif kind == "add":
            body.append(f"  cells[{dst}] = (uint8_t)(cells[{a}] + cells[{b}]);"
                        f"  // add wrap mod 256, {dist}")
        else:
            body.append(f"  cells[{dst}] = (uint8_t)(cells[{a}] * cells[{b}]);"
                        f"  // mul wrap mod 256, {dist}")
    op_init = ""  # straight-line code needs no runtime program table
    src = HEADER.format(
        ir_name=os.path.basename(args.ir_file),
        n_default=args.n_instances,
        n_inputs=len(in_cells),
        n_outputs=len(out_cells),
        max_cell=max_cell,
        n_ops=len(ops),
        in_cells=",".join(map(str, in_cells)),
        out_cells=",".join(map(str, out_cells)),
        prologue="\n".join(prologue),
        op_code="\n".join(body),
    )
    with open(args.out, "w") as f:
        f.write(src)
    total_cost = sum(rc(o[2]) + (rc(o[3]) if o[3] != o[2] else 0)
                     for o in ops if o[0] != "set")
    total_cost += sum(rc(o[1]) for o in ops if o[0] == "set" and False)  # sets are free
    total_cost += sum(rc(c) for c in out_cells)
    print(f"wrote {args.out}: {len(ops)} ops, {len(in_cells)} inputs, "
          f"{len(out_cells)} outputs, max cell {max_cell}")
    print(f"(cross-check: static cost of emitted read pattern = {total_cost})")


if __name__ == "__main__":
    main()
